"""Environment variable names shared across runtime boundaries."""

MINDWEFT_ATTACHMENT_DB_PATH_ENV = "MINDWEFT_ATTACHMENT_DB_PATH"
MINDWEFT_THREAD_DB_PATH_ENV = "MINDWEFT_THREAD_DB_PATH"
ATTACHMENT_DB_PATH_ENV = "MINIGENT_ATTACHMENT_DB_PATH"
THREAD_DB_PATH_ENV = "MINIGENT_THREAD_DB_PATH"
